### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by machadi** [machadi/PDL_1920_groupe-7#1]
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 5
	at java.lang.String.substring(String.java:1963)
	at fr.istic.pdl1819_grp5.ConverterToCsv.withoutTags(ConverterToCsv.java:355)
	at fr.istic.pdl1819_grp5.ConverterToCsv.writeInCsv(ConverterToCsv.java:297)
	at fr.istic.pdl1819_grp5.ConverterToCsv.convertHtmlTable(ConverterToCsv.java:244)
	at fr.istic.pdl1819_grp5.ConverterToCsv.convertFromHtml(ConverterToCsv.java:204)
	at fr.istic.pdl1819_grp5.WikipediaMatrix.getConvertResult(WikipediaMatrix.java:39)
	at fr.istic.pdl1819_grp5.wikiMain.extracteurenmarche(wikiMain.java:91)
	at fr.istic.pdl1819_grp5.wikiMain.main(wikiMain.java:202)

Process finished with exit code 1

**Comment by machadi** [comment]
change parameter from String codeCountry = s.substring(2,4); to String codeCountry = s.substring(2,5);  inthe class ConverteToCSV at the ligne 357

**Comment by machadi** [comment]
change parameter from String codeCountry = s.substring(2,4); to String codeCountry = s.substring(2,5);  inthe class ConverteToCSV at the ligne 357 .
